definitions:
  models.Task:
    properties:
      activeAt:
        type: string
      done:
        type: boolean
      id:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  description: This is a simple TODO List API (hl)
  title: TODO List API
  version: "1.0"
paths:
  /api/todo-list/tasks:
    get:
      consumes:
      - application/json
      description: Retrieves a list of tasks
      parameters:
      - default: active
        description: Task status
        enum:
        - active
        - done
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of tasks
          schema:
            items:
              $ref: '#/definitions/models.Task'
            type: array
      summary: Get tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Creates a new task
      parameters:
      - description: Task to create
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "201":
          description: id of the created task
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            type: string
      summary: Create a new task
      tags:
      - tasks
  /api/todo-list/tasks/{ID}:
    delete:
      description: Deletes a task
      parameters:
      - description: Task ID
        in: path
        name: ID
        required: true
        type: string
      responses:
        "204":
          description: Task deleted successfully
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Delete a task
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: Updates an existing task
      parameters:
      - description: Task ID
        in: path
        name: ID
        required: true
        type: string
      - description: Updated task data
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "204":
          description: Task updated successfully
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Update an existing task
      tags:
      - tasks
  /api/todo-list/tasks/{ID}/done:
    put:
      description: Marks a task as done
      parameters:
      - description: Task ID
        in: path
        name: ID
        required: true
        type: string
      responses:
        "204":
          description: Task completed successfully
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Complete a task
      tags:
      - tasks
  /health:
    get:
      description: Check if the service is running.
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check
swagger: "2.0"
